/**
 * Repository adapter for the shared migration engine. Traversal is bounded,
 * symbolic links are ignored, and Git is always invoked with an argument array
 * so source-controlled branch names can never become shell commands.
 */

import { compileSync } from '@mdx-js/mdx'
import { spawn } from 'node:child_process'
import {
  existsSync,
  lstatSync,
  readFileSync,
  readdirSync,
} from 'node:fs'
import { createRequire } from 'node:module'
import { basename, dirname, extname, relative, resolve as resolvePath } from 'node:path'

import { parse as parseYaml } from 'yaml'

import { createComponentMigrator, declarationsReferenceBrowserGlobal, hasAnyFunctionValuedProp, propsTargetExtractedClientComponent } from './components.js'

import {
  projectDocusaurusNavigation,
  readDocusaurusSidebars,
  rewriteDocusaurusLinks,
  resolveDocusaurusPageIdentity,
  type DocusaurusPageDescriptor,
  type DocusaurusSidebars,
} from './docusaurus.js'
import { projectFernNavigation, readFernConfig } from './fern.js'
import { detectUnsupportedFernComponents, escapeFernLiteralBraces, functionDeclaredNames, parseMarkdownPage } from './mdx.js'
import {
  addMintlifyDirectoryRedirects,
  addMintlifyHomepageRedirects,
  buildNavigationFromPages,
  isDocumentationExtension,
  projectMintlifyNavigation,
  pruneMissingNavigationPages,
  readMintlifyConfig,
} from './navigation.js'
import {
  normalizeAssetPath,
  mintlifyLocalizedReference,
  pageIdFromReference,
  resolveWithin,
  trimEdgeSlashes,
  trimTrailingSlashes,
} from './path.js'
import type {
  MigrationAsset,
  MigrationBundle,
  MigrationDocsConfig,
  MigrationNavigationGroup,
  MigrationPage,
  MigrationPlatform,
  MigrationWarning,
} from './types.js'

const MAX_SOURCE_FILES = 5_000
const MAX_PAGE_BYTES = 2_000_000
const MAX_ASSET_BYTES = 25_000_000
const MAX_TOTAL_ASSET_BYTES = 500_000_000
const IGNORED_DIRECTORIES = new Set([
  '.git', '.github', '.next', '.turbo', '.vercel', '.vscode',
  'node_modules', 'dist', 'build', 'coverage',
])
const ASSET_DIRECTORIES = new Set(['assets', 'images', 'img', 'media', 'public', 'static'])
const ASSET_EXTENSIONS = new Set([
  '.avif', '.bmp', '.gif', '.ico', '.jpeg', '.jpg', '.mp3', '.mp4',
  '.pdf', '.png', '.svg', '.webm', '.webp',
])
const REPOSITORY_ONLY_DOCUMENTS = new Set([
  'agents.md', 'claude.md', 'code_of_conduct.md', 'contributing.md',
  'license.md', 'readme.md', 'security.md',
])
const SNIPPET_DIRECTORIES = new Set(['snippets', '_snippets', 'partials', '_partials'])
// Matches a default import (`import Name from '...'`), a default-as-named
// import (`import { default as Name } from '...'`), and a plain named import
// (`import { Name } from '...'`) — Mintlify snippets can export either way.
const SNIPPET_IMPORT_PATTERN = /^import\s+(?:\{\s*(?:default\s+as\s+)?([A-Z][A-Za-z0-9_]*)\s*\}|([A-Z][A-Za-z0-9_]*))\s+from\s+['"]([^'"]+\.mdx?)['"]\s*;?(?:\s*\/\/.*)?$/gm
const MINTIGNORE_FILENAME = '.mintignore'
interface IgnoreMatcher {
  add(patterns: string): IgnoreMatcher
  ignores(pathname: string): boolean
}
// `ignore`'s CJS default export is mistyped under NodeNext module resolution
// (the default import resolves to the whole module namespace); load it
// through `require` and type it locally instead of fighting the interop.
const createIgnoreMatcher = createRequire(import.meta.url)('ignore') as () => IgnoreMatcher

/** Dotfile directories (`.tooling`, `.vale`, tool/editor config, ...) never hold docs pages. */
function isIgnoredDirectory(name: string): boolean {
  return name.startsWith('.') || IGNORED_DIRECTORIES.has(name)
}

const OPENAPI_FILENAMES = new Set([
  'openapi.json', 'openapi.yaml', 'openapi.yml',
  'swagger.json', 'swagger.yaml', 'swagger.yml',
])

export interface GitHubRepositorySource {
  owner: string
  repo: string
  branch: string
  docsDir: string
  cloneUrl: string
}

export interface RepositoryMigrationOptions {
  repositoryDir: string
  sourceUrl: string
  docsDir?: string
  platform?: MigrationPlatform
  /** @internal Prefix used by additional Docusaurus docs-plugin instances. */
  docusaurusRoutePrefix?: string
  /** @internal Prevent recursive discovery while importing one plugin root. */
  docusaurusSkipPlugins?: boolean
  /** @internal Additional docs plugins default to autogenerated navigation. */
  docusaurusSkipSidebar?: boolean
  /** @internal Static assets are shared across docs-plugin instances. */
  docusaurusSkipAssets?: boolean
}

interface DocusaurusPluginRoot {
  docsDir: string
  routePrefix: string
}

const DOCUSAURUS_CONFIG_FILENAMES = [
  'docusaurus.config.js',
  'docusaurus.config.ts',
  'docusaurus.config.mjs',
]

function hasDocusaurusConfig(directory: string): boolean {
  return DOCUSAURUS_CONFIG_FILENAMES.some((filename) => {
    const path = resolveWithin(directory, filename)
    return existsSync(path) && lstatSync(path).isFile()
  })
}

function hasMintlifyConfig(directory: string): boolean {
  return ['docs.json', 'mint.json'].some((filename) => {
    const path = resolveWithin(directory, filename)
    if (!existsSync(path) || !lstatSync(path).isFile()) return false
    if (filename === 'mint.json') return true
    try {
      const config = JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown>
      return String(config.$schema ?? '').includes('mintlify') || 'navigation' in config
    } catch {
      return false
    }
  })
}

function findMintlifyProjectRoot(repositoryDir: string, docsDir?: string): string | null {
  if (docsDir !== undefined) {
    let candidate = trimTrailingSlashes(docsDir)
    while (true) {
      const path = resolveWithin(repositoryDir, candidate || '.')
      if (hasMintlifyConfig(path)) return path
      if (!candidate) break
      const parent = dirname(candidate)
      candidate = parent === '.' ? '' : parent
    }
  }
  const queue: Array<{ directory: string; depth: number }> = [{ directory: repositoryDir, depth: 0 }]
  let visited = 0
  while (queue.length > 0 && visited < 500) {
    const current = queue.shift()!
    visited++
    if (hasMintlifyConfig(current.directory)) return current.directory
    if (current.depth >= 4) continue
    for (const entry of readdirSync(current.directory, { withFileTypes: true })) {
      if (!entry.isDirectory() || entry.isSymbolicLink() || isIgnoredDirectory(entry.name)) continue
      queue.push({ directory: resolveWithin(current.directory, entry.name), depth: current.depth + 1 })
    }
  }
  return null
}

function hasFernConfig(directory: string): boolean {
  return ['docs.yml', 'fern.config.json'].every((filename) => {
    const path = resolveWithin(directory, filename)
    return existsSync(path) && lstatSync(path).isFile()
  })
}

function findFernProjectRoot(repositoryDir: string, docsDir?: string): string | null {
  if (docsDir !== undefined) {
    let candidate = trimTrailingSlashes(docsDir)
    while (true) {
      const path = resolveWithin(repositoryDir, candidate || '.')
      if (hasFernConfig(path)) return path
      if (!candidate) break
      const parent = dirname(candidate)
      candidate = parent === '.' ? '' : parent
    }
  }
  const queue: Array<{ directory: string; depth: number }> = [{ directory: repositoryDir, depth: 0 }]
  let visited = 0
  while (queue.length > 0 && visited < 500) {
    const current = queue.shift()!
    visited++
    if (hasFernConfig(current.directory)) return current.directory
    if (current.depth >= 4) continue
    for (const entry of readdirSync(current.directory, { withFileTypes: true })) {
      if (!entry.isDirectory() || entry.isSymbolicLink() || isIgnoredDirectory(entry.name)) continue
      queue.push({ directory: resolveWithin(current.directory, entry.name), depth: current.depth + 1 })
    }
  }
  return null
}

function findDocusaurusProjectRoot(repositoryDir: string, docsDir?: string): string | null {
  if (docsDir !== undefined) {
    let candidate = trimTrailingSlashes(docsDir)
    while (true) {
      const path = resolveWithin(repositoryDir, candidate || '.')
      if (hasDocusaurusConfig(path)) return path
      if (!candidate) break
      const parent = dirname(candidate)
      candidate = parent === '.' ? '' : parent
    }
  }

  const queue: Array<{ directory: string; depth: number }> = [{ directory: repositoryDir, depth: 0 }]
  let visited = 0
  while (queue.length > 0 && visited < 500) {
    const current = queue.shift()!
    visited++
    if (hasDocusaurusConfig(current.directory)) return current.directory
    if (current.depth >= 4) continue
    for (const entry of readdirSync(current.directory, { withFileTypes: true })) {
      if (!entry.isDirectory() || entry.isSymbolicLink() || isIgnoredDirectory(entry.name)) continue
      queue.push({
        directory: resolveWithin(current.directory, entry.name),
        depth: current.depth + 1,
      })
    }
  }
  return null
}

function readDocusaurusConfigSource(projectRoot: string): string {
  const path = DOCUSAURUS_CONFIG_FILENAMES
    .map((filename) => resolveWithin(projectRoot, filename))
    .find((candidate) => existsSync(candidate) && lstatSync(candidate).isFile())
  if (!path || lstatSync(path).size > 1_000_000) return ''
  return readFileSync(path, 'utf8')
}

function primaryDocusaurusDocsDirectory(projectRoot: string): string {
  const source = readDocusaurusConfigSource(projectRoot)
  const configured = source.match(/\bdocs\s*:\s*\{[\s\S]{0,4000}?\bpath\s*:\s*(['"])([^'"]+)\1/)?.[2]
  return trimTrailingSlashes(configured?.replace(/^\.\//, '') ?? '') || 'docs'
}

function additionalDocusaurusPluginRoots(
  repositoryDir: string,
  projectRoot: string,
): Array<DocusaurusPluginRoot> {
  const source = readDocusaurusConfigSource(projectRoot)
  const projectRelative = relative(repositoryDir, projectRoot).replace(/\\/g, '/')
  const plugins: Array<DocusaurusPluginRoot> = []
  const matcher = /['"]@docusaurus\/plugin-content-docs['"][\s\S]{0,3000}?\bpath\s*:\s*(['"])([^'"]+)\1[\s\S]{0,1000}?\brouteBasePath\s*:\s*(['"])([^'"]+)\3/g
  for (const match of source.matchAll(matcher)) {
    const localPath = trimTrailingSlashes(match[2].replace(/^\.\//, ''))
    const routePrefix = trimEdgeSlashes(match[4])
    if (!localPath || !routePrefix) continue
    const docsDir = [projectRelative, localPath].filter(Boolean).join('/')
    const absolute = resolveWithin(repositoryDir, docsDir)
    if (!existsSync(absolute) || !lstatSync(absolute).isDirectory()) continue
    plugins.push({ docsDir, routePrefix })
  }
  return plugins
}

/** Parse and validate a public GitHub repository URL. */
export function parseGitHubRepositoryUrl(rawUrl: string): GitHubRepositorySource {
  let url: URL
  try {
    url = new URL(rawUrl)
  } catch {
    throw new Error(`Invalid GitHub URL: ${rawUrl}`)
  }
  if (url.protocol !== 'https:' || url.hostname.toLowerCase() !== 'github.com') {
    throw new Error('Repository migrations require an https://github.com URL.')
  }
  if (url.username || url.password || url.port) {
    throw new Error('GitHub repository URLs cannot include credentials or custom ports.')
  }
  const segments = url.pathname.split('/').filter(Boolean).map(decodeURIComponent)
  const [owner, rawRepo] = segments
  const repo = rawRepo?.replace(/\.git$/i, '')
  const safeName = /^[A-Za-z0-9_.-]+$/
  if (!owner || !repo || !safeName.test(owner) || !safeName.test(repo)) {
    throw new Error('GitHub URL must include a valid owner and repository name.')
  }
  let branch = 'HEAD'
  let docsDir = ''
  if (segments[2] === 'tree' && segments[3]) {
    branch = segments[3]
    docsDir = segments.slice(4).join('/')
  }
  return {
    owner,
    repo,
    branch,
    docsDir,
    cloneUrl: `https://github.com/${owner}/${repo}.git`,
  }
}

/** Clone a repository without a shell; callers own and remove `targetDir`. */
export async function cloneGitHubRepository(
  source: GitHubRepositorySource,
  targetDir: string,
): Promise<void> {
  const args = ['clone', '--depth', '1', '--single-branch']
  if (source.branch !== 'HEAD') args.push('--branch', source.branch)
  args.push('--', source.cloneUrl, targetDir)
  await new Promise<void>((resolve, reject) => {
    const child = spawn('git', args, { stdio: ['ignore', 'ignore', 'pipe'] })
    let stderr = ''
    child.stderr.setEncoding('utf8')
    child.stderr.on('data', (chunk: string) => {
      if (stderr.length < 16_000) stderr += chunk
    })
    child.on('error', reject)
    child.on('close', (code) => {
      if (code === 0) resolve()
      else reject(new Error(`Failed to clone ${source.owner}/${source.repo}: ${stderr.trim() || `git exited ${code}`}`))
    })
  })
}

/** Detect a supported repository docs platform from unambiguous config files. */
export function detectRepositoryPlatform(repositoryDir: string, docsDir?: string): MigrationPlatform {
  if (findMintlifyProjectRoot(repositoryDir, docsDir)) return 'mintlify'
  if (findFernProjectRoot(repositoryDir, docsDir)) return 'fern'
  const selectedRoot = docsDir === undefined ? repositoryDir : resolveWithin(repositoryDir, docsDir || '.')
  const docsJson = resolveWithin(selectedRoot, 'docs.json')
  if (existsSync(docsJson)) {
    try {
      const config = JSON.parse(readFileSync(docsJson, 'utf8')) as Record<string, unknown>
      if (Array.isArray(config.tabs)) return 'thally'
    } catch {
      // A malformed source config is reported later; platform detection falls through.
    }
  }
  if (['docusaurus.config.js', 'docusaurus.config.ts', 'docusaurus.config.mjs']
    .some((name) => existsSync(resolveWithin(repositoryDir, name)))) return 'docusaurus'
  if (findDocusaurusProjectRoot(repositoryDir)) return 'docusaurus'
  if (existsSync(resolveWithin(repositoryDir, 'SUMMARY.md'))) return 'gitbook'
  if (existsSync(resolveWithin(repositoryDir, '.vitepress'))) return 'vitepress'
  if (['astro.config.mjs', 'astro.config.ts']
    .some((name) => existsSync(resolveWithin(repositoryDir, name)))) return 'starlight'
  if (['pages/_meta.json', '_meta.json']
    .some((name) => existsSync(resolveWithin(repositoryDir, name)))) return 'nextra'
  return 'unknown'
}

function containsMarkdown(directory: string, depth = 0): boolean {
  if (depth > 4) return false
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (isIgnoredDirectory(entry.name) || entry.isSymbolicLink()) continue
    const path = resolveWithin(directory, entry.name)
    if (entry.isFile() && ['.md', '.mdx'].includes(extname(entry.name).toLowerCase())) return true
    if (entry.isDirectory() && containsMarkdown(path, depth + 1)) return true
  }
  return false
}

/** Pick the first conventional content root containing Markdown. */
export function detectRepositoryDocsDir(repositoryDir: string): string {
  for (const candidate of ['docs', 'documentation', 'content', 'pages', 'src/content', 'src/pages', 'guide', 'guides', '']) {
    const path = resolveWithin(repositoryDir, candidate)
    if (existsSync(path) && lstatSync(path).isDirectory() && containsMarkdown(path)) return candidate
  }
  return ''
}

interface ScannedFile {
  absolutePath: string
  relativePath: string
}

function scanFiles(root: string): Array<ScannedFile> {
  const files: Array<ScannedFile> = []
  function visit(directory: string): void {
    if (files.length >= MAX_SOURCE_FILES) return
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      if (files.length >= MAX_SOURCE_FILES) return
      if (isIgnoredDirectory(entry.name) || entry.isSymbolicLink()) continue
      const path = resolveWithin(directory, entry.name)
      if (entry.isDirectory()) visit(path)
      else if (entry.isFile()) files.push({ absolutePath: path, relativePath: relative(root, path).replace(/\\/g, '/') })
    }
  }
  visit(root)
  return files
}

/**
 * Mintlify excludes paths from the docs site with a gitignore-style
 * `.mintignore` at the project root (see Mintlify's docs). Honoring it keeps
 * internal tooling directories like `agent-context/` out of the migration
 * even though they aren't dotfile directories.
 */
function readMintignoreMatcher(mintlifyRoot: string): IgnoreMatcher | null {
  const path = resolveWithin(mintlifyRoot, MINTIGNORE_FILENAME)
  if (!existsSync(path) || !lstatSync(path).isFile()) return null
  return createIgnoreMatcher().add(readFileSync(path, 'utf8'))
}

/**
 * Compile-check a page body with the same MDX compiler the scaffold's
 * runtime build uses (`@mdx-js/mdx`). A single malformed page must never
 * abort `scripts/build-runtime-sources.mts` for the whole project, so
 * migration excludes it up front instead and reports why.
 */
function invalidMdxReason(body: string): string | null {
  try {
    compileSync(body, { outputFormat: 'program' })
    return null
  } catch (error) {
    return error instanceof Error ? error.message : String(error)
  }
}

const HEX_COLOR = /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i

/** Extract Mintlify's `colors.{primary,light,dark}` theme hexes, if valid. */
function mintlifyThemeColors(value: unknown): { primary?: string; light?: string; dark?: string } | undefined {
  if (!value || typeof value !== 'object') return undefined
  const source = value as Record<string, unknown>
  const colors: { primary?: string; light?: string; dark?: string } = {}
  for (const key of ['primary', 'light', 'dark'] as const) {
    if (typeof source[key] === 'string' && HEX_COLOR.test(source[key])) colors[key] = source[key]
  }
  return Object.keys(colors).length > 0 ? colors : undefined
}

/**
 * Extract Fern's `colors.accent-primary` (a hex string, or `{light, dark}`),
 * if valid. Fern's `light`/`dark` are normal (each names the mode it
 * paints), unlike Mintlify's inverted schema that `site.colors` otherwise
 * follows, so they're swapped onto Mintlify's `{light, dark}` keys here to
 * give downstream consumers (`updateSiteConfig`) one consistent contract.
 */
function fernThemeColors(value: unknown): { primary?: string; light?: string; dark?: string } | undefined {
  if (!value || typeof value !== 'object') return undefined
  const accent = (value as Record<string, unknown>)['accent-primary']
  if (typeof accent === 'string') return HEX_COLOR.test(accent) ? { primary: accent } : undefined
  if (!accent || typeof accent !== 'object') return undefined
  const source = accent as Record<string, unknown>
  const lightMode = typeof source.light === 'string' && HEX_COLOR.test(source.light) ? source.light : undefined
  const darkMode = typeof source.dark === 'string' && HEX_COLOR.test(source.dark) ? source.dark : undefined
  const colors: { light?: string; dark?: string } = {}
  if (darkMode) colors.light = darkMode
  if (lightMode) colors.dark = lightMode
  return Object.keys(colors).length > 0 ? colors : undefined
}

function normalizedReferenceKey(value: string): string {
  return value.split(/[?#]/, 1)[0]
    .replace(/^\/+/, '')
    .replace(/\\/g, '/')
    .replace(/\.(?:mdx?|rst|txt)$/i, '')
    .replace(/\/(?:index|readme)$/i, '')
    .replace(/^(?:index|readme)$/i, '') || 'introduction'
}

function exactReferenceKey(value: string): string {
  return value.split(/[?#]/, 1)[0]
    .replace(/^\/+/, '')
    .replace(/\\/g, '/')
    .replace(/\.(?:mdx?|rst|txt)$/i, '')
}

function findOpenApi(files: Array<ScannedFile>): ScannedFile | null {
  return files.find((file) => OPENAPI_FILENAMES.has(basename(file.relativePath).toLowerCase())) ?? null
}

function findConfiguredMintlifyOpenApi(
  config: Record<string, unknown> | null,
  files: Array<ScannedFile>,
): ScannedFile | null {
  const api = config?.api && typeof config.api === 'object' && !Array.isArray(config.api)
    ? config.api as Record<string, unknown>
    : null
  const configured = typeof api?.openapi === 'string'
    ? [api.openapi]
    : Array.isArray(api?.openapi) ? api.openapi.filter((value): value is string => typeof value === 'string') : []
  for (const reference of configured) {
    if (/^(?:https?:)?\/\//i.test(reference)) continue
    const key = reference.split(/[?#]/, 1)[0].replace(/^\/+/, '').replace(/\\/g, '/')
    const match = files.find((file) => file.relativePath === key)
    if (match) return match
  }
  return null
}

const MAX_FERN_GENERATORS_BYTES = 2_000_000

function fernGeneratorsOpenApiPaths(config: Record<string, unknown>): Array<string> {
  const api = config.api
  if (typeof api === 'string') return [api]
  if (!api || typeof api !== 'object' || Array.isArray(api)) return []
  const specs = (api as Record<string, unknown>).specs
  if (!Array.isArray(specs)) return []
  return specs.flatMap((spec) => {
    if (typeof spec === 'string') return [spec]
    if (!spec || typeof spec !== 'object' || Array.isArray(spec)) return []
    const openapi = (spec as Record<string, unknown>).openapi
    return typeof openapi === 'string' ? [openapi] : []
  })
}

function readFernGeneratorsConfig(path: string): Record<string, unknown> | null {
  if (!existsSync(path) || !lstatSync(path).isFile() || lstatSync(path).size > MAX_FERN_GENERATORS_BYTES) return null
  const parsed = parseYaml(readFileSync(path, 'utf8'))
  return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed as Record<string, unknown> : null
}

/**
 * Resolve the OpenAPI spec Fern's `generators.yml` configures for an API:
 * modern `api.specs[].openapi`, or the legacy top-level `api:` string.
 * Multi-API repos keep a `generators.yml` per API under `fern/apis/<name>/`;
 * single-API repos keep one at the Fern project root.
 *
 * The root `generators.yml` belongs to a *different* API only in a multi-API
 * repo, which Fern lays out under `fern/apis/`. So the root config is skipped
 * only when an explicit `api-name` is set AND a `fern/apis/` directory
 * exists; a single-API repo whose docs.yml still names its API keeps its tab.
 */
function fernOpenApiCandidateDirs(fernRoot: string, apiName: string | undefined, apiNameExplicit: boolean): Array<string> {
  const candidateDirs: Array<string> = []
  if (apiName) {
    try {
      candidateDirs.push(resolveWithin(fernRoot, `apis/${apiName}`))
    } catch {
      // Not a safe relative path (e.g. a display label, not a folder name).
    }
  }
  const apisDir = resolvePath(fernRoot, 'apis')
  const multiApi = existsSync(apisDir) && lstatSync(apisDir).isDirectory()
  if (!apiNameExplicit || !multiApi) candidateDirs.push(fernRoot)
  return candidateDirs
}

function findFernConfiguredOpenApi(
  fernRoot: string,
  repositoryDir: string,
  apiName: string | undefined,
  apiNameExplicit: boolean,
): ScannedFile | null {
  const candidateDirs = fernOpenApiCandidateDirs(fernRoot, apiName, apiNameExplicit)
  for (const dir of candidateDirs) {
    let config: Record<string, unknown> | null = null
    try {
      config = readFernGeneratorsConfig(resolveWithin(dir, 'generators.yml'))
    } catch {
      continue
    }
    if (!config) continue
    for (const specPath of fernGeneratorsOpenApiPaths(config)) {
      if (/^(?:https?:)?\/\//i.test(specPath)) continue
      try {
        const absolute = resolveWithin(dir, specPath)
        if (!existsSync(absolute) || !lstatSync(absolute).isFile()) continue
        return { absolutePath: absolute, relativePath: relative(repositoryDir, absolute).replace(/\\/g, '/') }
      } catch {
        // Outside the Fern root or otherwise unsafe; skip.
      }
    }
  }
  return null
}

/** Whether a Fern Definition (as opposed to a plain OpenAPI/AsyncAPI spec) backs this API. */
function fernDefinitionExists(fernRoot: string, apiName: string | undefined): boolean {
  const candidateDirs: Array<string> = []
  if (apiName) {
    try {
      candidateDirs.push(resolveWithin(fernRoot, `apis/${apiName}/definition`))
    } catch {
      // Not a safe relative path; skip.
    }
  }
  try {
    candidateDirs.push(resolveWithin(fernRoot, 'definition'))
  } catch {
    // Unreachable: 'definition' is always a safe relative segment.
  }
  return candidateDirs.some((dir) => existsSync(dir) && lstatSync(dir).isDirectory())
}

function withoutFrontmatter(value: string): string {
  return value.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '').trim()
}

function staticSnippetProperties(attributes: string): Map<string, string> {
  const properties = new Map<string, string>()
  const matcher = /\b([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?:"([^"]*)"|'([^']*)'|\{\s*"([^"]*)"\s*\}|\{\s*'([^']*)'\s*\})/g
  for (const match of attributes.matchAll(matcher)) {
    properties.set(match[1], match[2] ?? match[3] ?? match[4] ?? match[5] ?? '')
  }
  return properties
}

function interpolateSnippet(snippet: string, attributes: string): string {
  const properties = staticSnippetProperties(attributes)
  if (properties.size === 0) return snippet
  let fence = ''
  return snippet.split('\n').map((line) => {
    const marker = line.match(/^\s*(`{3,}|~{3,})/)?.[1]
    if (marker) {
      if (!fence) fence = marker[0]
      else if (marker[0] === fence) fence = ''
      return line
    }
    if (fence) return line
    return line.replace(/\{([A-Za-z_][A-Za-z0-9_]*)\}/g, (original, name: string) => {
      return properties.get(name) ?? original
    })
  }).join('\n')
}

function resolveSnippetPath(
  sourcePath: string,
  currentFile: string,
  repositoryRoot: string,
  siteRoot: string,
): string {
  const repositoryRelative = sourcePath.startsWith('@site/')
    ? relative(repositoryRoot, resolveWithin(siteRoot, sourcePath.slice('@site/'.length))).replace(/\\/g, '/')
    : sourcePath.startsWith('/')
      ? relative(repositoryRoot, resolveWithin(siteRoot, sourcePath.replace(/^\/+/, ''))).replace(/\\/g, '/')
      : relative(repositoryRoot, resolvePath(dirname(currentFile), sourcePath)).replace(/\\/g, '/')
  const candidate = resolveWithin(repositoryRoot, repositoryRelative)
  resolveWithin(repositoryRoot, relative(repositoryRoot, candidate))
  return candidate
}

function globalSnippetAliases(
  files: Array<ScannedFile>,
  repositoryRoot: string,
  siteRoot: string,
): Map<string, string> {
  const aliases = new Map<string, string>()
  for (const file of files) {
    const segments = file.relativePath.split('/')
    if (!segments.some((segment) => SNIPPET_DIRECTORIES.has(segment.toLowerCase()))) continue
    const basenameWithoutExtension = basename(file.relativePath).replace(/\.mdx?$/i, '')
    const conventionalAlias = basenameWithoutExtension
      .split(/[^A-Za-z0-9]+/)
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
    if (conventionalAlias) aliases.set(conventionalAlias, file.absolutePath)
  }
  for (const file of files) {
    if (!['.md', '.mdx'].includes(extname(file.relativePath).toLowerCase())) continue
    const raw = readFileSync(file.absolutePath, 'utf8')
    for (const match of raw.matchAll(SNIPPET_IMPORT_PATTERN)) {
      try {
        const componentName = match[1] ?? match[2]
        const candidate = resolveSnippetPath(match[3], file.absolutePath, repositoryRoot, siteRoot)
        if (existsSync(candidate) && lstatSync(candidate).isFile()) {
          aliases.set(componentName, candidate)
        }
      } catch {
        // The page-local inliner emits the actionable warning when it reaches
        // an unsafe or missing import. Global discovery is best-effort only.
      }
    }
  }
  return aliases
}

function repositoryAssetHref(
  value: string,
  currentFile: string,
  siteRoot: string,
): string | null {
  const isBracketed = value.startsWith('<') && value.endsWith('>')
  const raw = isBracketed ? value.slice(1, -1) : value
  if (!raw || raw.startsWith('#') || /^(?:[a-z][a-z0-9+.-]*:|\/\/)/i.test(raw)) return null
  const suffixIndex = raw.search(/[?#]/)
  const pathname = suffixIndex >= 0 ? raw.slice(0, suffixIndex) : raw
  const suffix = suffixIndex >= 0 ? raw.slice(suffixIndex) : ''
  let decodedPath: string
  try {
    decodedPath = decodeURIComponent(pathname)
  } catch {
    return null
  }
  if (!ASSET_EXTENSIONS.has(extname(decodedPath).toLowerCase())) return null
  try {
    const candidate = decodedPath.startsWith('/')
      ? resolveWithin(siteRoot, decodedPath.replace(/^\/+/, ''))
      : resolveWithin(dirname(currentFile), decodedPath)
    // Mintlify's deploy root is the directory containing docs.json. Do not
    // copy or expose a relative reference that escapes that project boundary.
    const siteRelative = relative(siteRoot, candidate).replace(/\\/g, '/')
    resolveWithin(siteRoot, siteRelative)
    if (!existsSync(candidate) || !lstatSync(candidate).isFile()) return null
    const normalized = normalizeAssetPath(siteRelative)
    if (!normalized) return null
    const rewritten = `/${normalized}${suffix}`
    // Markdown destinations containing parentheses must stay angle-bracketed;
    // removing the wrapper makes CommonMark terminate the URL too early.
    return isBracketed ? `<${rewritten}>` : rewritten
  } catch {
    return null
  }
}

/**
 * Rewrite links to a page whose Fern frontmatter `slug` replaced its docs.yml
 * hierarchy. Other pages still spell the link the "natural" nested way, so
 * this runs across every page's body, not just the renamed page's own.
 */
function rewriteFernIdRenameLinks(body: string, renames: Map<string, string>): string {
  let codeFence: string | null = null
  return body.split('\n').map((line) => {
    const fence = line.match(/^\s*(`{3,}|~{3,})/)
    if (fence) {
      if (!codeFence) codeFence = fence[1][0]
      else if (fence[1][0] === codeFence) codeFence = null
      return line
    }
    if (codeFence) return line
    const rewriteTarget = (target: string): string => {
      const suffixIndex = target.search(/[?#]/)
      const path = (suffixIndex >= 0 ? target.slice(0, suffixIndex) : target).replace(/^\/+/, '')
      const suffix = suffixIndex >= 0 ? target.slice(suffixIndex) : ''
      const renamed = renames.get(path)
      return renamed ? `/${renamed}${suffix}` : target
    }
    return line
      .replace(/(\]\()\/([^\s)]+)(?=[\s)]|$)/g, (_match, prefix: string, target: string) => `${prefix}${rewriteTarget(`/${target}`)}`)
      .replace(/(\bhref=")\/([^"]+)(")/g, (_match, prefix: string, target: string, suffix: string) => `${prefix}${rewriteTarget(`/${target}`)}${suffix}`)
  }).join('\n')
}

function rewriteRepositoryAssetLinks(body: string, currentFile: string, siteRoot: string): string {
  return body
    .replace(/(!?\[[^\]]*\]\()(<[^>]+>|[^)\s]+)([^)]*\))/g, (
      original,
      opening: string,
      destination: string,
      closing: string,
    ) => {
      const rewritten = repositoryAssetHref(destination, currentFile, siteRoot)
      return rewritten ? `${opening}${rewritten}${closing}` : original
    })
    .replace(/\b(src|img|image|href)=(['"])([^'"]+)\2/g, (
      original,
      property: string,
      quote: string,
      destination: string,
    ) => {
      const rewritten = repositoryAssetHref(destination, currentFile, siteRoot)
      return rewritten ? `${property}=${quote}${rewritten}${quote}` : original
    })
}

const LOCAL_EXPORT_DECLARATION = /^\s*export\s+(?:const|let|var|function|class|async\s+function)\s+([A-Za-z_$][\w$]*)/

/**
 * Names a page declares itself with a top-level `export const/function/class`.
 * Mintlify treats every file under `/snippets/` as an implicitly available
 * global component keyed by its filename, so a page that happens to declare
 * an inline component with the same name (e.g. both `snippets/counter.mdx`
 * and a page's own `export const Counter = ...`) must keep its local
 * declaration: forcing the unrelated global snippet's source in over a
 * `<Counter />` usage duplicates the export and breaks the compiled module.
 */
function locallyDeclaredNames(raw: string): Set<string> {
  const names = new Set<string>()
  let codeFence: string | null = null
  for (const line of raw.split('\n')) {
    const codeMatch = line.match(/^\s*(`{3,}|~{3,})/)
    if (codeMatch) {
      if (!codeFence) codeFence = codeMatch[1][0]
      else if (codeMatch[1][0] === codeFence) codeFence = null
      continue
    }
    if (codeFence) continue
    const declared = line.match(LOCAL_EXPORT_DECLARATION)?.[1]
    if (declared) names.add(declared)
  }
  return names
}

function inlineMdxSnippets(
  raw: string,
  currentFile: string,
  repositoryRoot: string,
  warnings: Array<MigrationWarning>,
  depth = 0,
  siteRoot = repositoryRoot,
  globalAliases: Map<string, string> = new Map(),
): string {
  if (depth >= 8) return raw
  const snippets = new Map<string, string>()
  const withoutImports = raw.replace(
    SNIPPET_IMPORT_PATTERN,
    (_statement, namedComponent: string | undefined, defaultComponent: string | undefined, sourcePath: string) => {
      const componentName = (namedComponent ?? defaultComponent) as string
      try {
        const candidate = resolveSnippetPath(sourcePath, currentFile, repositoryRoot, siteRoot)
        if (!existsSync(candidate) || !lstatSync(candidate).isFile()) throw new Error('file not found')
        const nested = inlineMdxSnippets(
          withoutFrontmatter(readFileSync(candidate, 'utf8')),
          candidate,
          repositoryRoot,
          warnings,
          depth + 1,
          siteRoot,
          globalAliases,
        )
        snippets.set(componentName, nested)
        return ''
      } catch {
        warnings.push({
          code: 'missing-page',
          message: `Imported snippet ${sourcePath} could not be resolved and was left as a comment.`,
          source: relative(repositoryRoot, currentFile).replace(/\\/g, '/'),
        })
        snippets.set(componentName, `{/* Missing imported snippet: ${sourcePath} */}`)
        return ''
      }
    },
  )
  // Mintlify resolves snippet imports across its MDX compilation graph. Some
  // real sites consequently reuse an alias on a page that does not repeat the
  // import declaration. Recover those aliases deterministically from imports
  // elsewhere in the same docs project.
  const localNames = locallyDeclaredNames(withoutImports)
  for (const [componentName, candidate] of globalAliases) {
    if (snippets.has(componentName) || localNames.has(componentName)
      || !new RegExp(`<${componentName}(?:\\s|/?>)`).test(withoutImports)) continue
    const nested = inlineMdxSnippets(
      withoutFrontmatter(readFileSync(candidate, 'utf8')),
      candidate,
      repositoryRoot,
      warnings,
      depth + 1,
      siteRoot,
      globalAliases,
    )
    snippets.set(componentName, nested)
  }
  let result = withoutImports
  for (const [componentName, snippet] of snippets) {
    result = result
      .replace(new RegExp(`<${componentName}((?:\\s[^>]*)?)\\s*/>`, 'g'), (_tag, attributes: string) => {
        return interpolateSnippet(snippet, attributes)
      })
      .replace(new RegExp(`<${componentName}((?:\\s[^>]*)?)>(?:[\\s\\S]*?)<\\/${componentName}>`, 'g'), (_tag, attributes: string) => {
        return interpolateSnippet(snippet, attributes)
      })
  }
  return result
}

function injectOpenApi(config: MigrationDocsConfig, filename: string, preferredTabLabel?: string): MigrationDocsConfig {
  const tabs = config.tabs.map((tab) => ({ ...tab }))
  const apiTab = (preferredTabLabel ? tabs.find((tab) => tab.tab === preferredTabLabel) : undefined)
    ?? tabs.find((tab) => tab.tab.toLowerCase().includes('api'))
  if (apiTab) apiTab.api = { source: `/${filename}`, navigation: false }
  else tabs.push({ tab: preferredTabLabel ?? 'API Reference', api: { source: `/${filename}` } })
  return { ...config, tabs }
}

/** Identify component ownership independently of checkout paths and URL syntax. */
function componentSourceIdentity(sourceUrl: string, repositoryDir: string, siteRoot: string): string {
  const url = new URL(sourceUrl)
  // A GitHub tree URL and the repository root identify the same source. Branch
  // changes should update its components, while separate monorepo sites must
  // retain independent namespaces even if their snippet filenames coincide.
  // Credentials, queries and fragments are not source identity and never feed
  // generated names; only the canonical origin/path and docs root participate.
  const repository = url.hostname.toLowerCase() === 'github.com'
    ? `https://github.com/${url.pathname.split('/').filter(Boolean).slice(0, 2).join('/').replace(/\.git$/i, '').toLowerCase()}`
    : `${url.origin}${trimTrailingSlashes(url.pathname)}`
  return JSON.stringify([repository, relative(repositoryDir, siteRoot).replace(/\\/g, '/')])
}

/** Import an already-available repository directory into a canonical bundle. */
export function migrateRepository(options: RepositoryMigrationOptions): MigrationBundle {
  const repositoryDir = options.repositoryDir
  const platform = options.platform ?? detectRepositoryPlatform(repositoryDir, options.docsDir)
  const mintlifyProjectRoot = platform === 'mintlify'
    ? findMintlifyProjectRoot(repositoryDir, options.docsDir)
    : null
  const docusaurusProjectRoot = platform === 'docusaurus'
    ? findDocusaurusProjectRoot(repositoryDir, options.docsDir)
    : null
  const fernProjectRoot = platform === 'fern'
    ? findFernProjectRoot(repositoryDir, options.docsDir)
    : null
  const configuredDocsDir = (() => {
    if (options.docsDir !== undefined) {
      const selected = resolveWithin(repositoryDir, options.docsDir || '.')
      if (platform === 'docusaurus' && hasDocusaurusConfig(selected)) {
        const projectRelative = relative(repositoryDir, selected).replace(/\\/g, '/')
        return [projectRelative, primaryDocusaurusDocsDirectory(selected)].filter(Boolean).join('/')
      }
      return options.docsDir
    }
    if (docusaurusProjectRoot) {
      const projectRelative = relative(repositoryDir, docusaurusProjectRoot).replace(/\\/g, '/')
      return [projectRelative, primaryDocusaurusDocsDirectory(docusaurusProjectRoot)].filter(Boolean).join('/')
    }
    if (platform === 'mintlify' && mintlifyProjectRoot) {
      return relative(repositoryDir, mintlifyProjectRoot).replace(/\\/g, '/')
    }
    if (platform === 'fern' && fernProjectRoot) {
      return relative(repositoryDir, fernProjectRoot).replace(/\\/g, '/')
    }
    return platform === 'mintlify' ? '' : detectRepositoryDocsDir(repositoryDir)
  })()
  const warnings: Array<MigrationWarning> = []
  // Only the current, default-locale docs are imported (`configuredDocsDir`,
  // below, never points inside these). Thally has no versions concept and
  // Docusaurus' own i18n content lives in a separate tree this adapter does
  // not project, so both are reported rather than silently dropped.
  if (platform === 'docusaurus' && docusaurusProjectRoot) {
    for (const [directory, label] of [
      ['versioned_docs', 'versioned docs'],
      ['versioned_sidebars', 'versioned sidebars'],
    ] as const) {
      const path = resolveWithin(docusaurusProjectRoot, directory)
      if (!existsSync(path) || !lstatSync(path).isDirectory()) continue
      const versions = readdirSync(path, { withFileTypes: true }).filter((entry) => entry.isDirectory()).map((entry) => entry.name)
      if (versions.length) warnings.push({
        code: 'unsupported-config',
        message: `Docusaurus ${label} were skipped; only current docs were imported. Skipped: ${versions.join(', ')}.`,
        source: directory,
      })
    }
    const i18nPath = resolveWithin(docusaurusProjectRoot, 'i18n')
    if (existsSync(i18nPath) && lstatSync(i18nPath).isDirectory()) {
      const locales = readdirSync(i18nPath, { withFileTypes: true }).filter((entry) => entry.isDirectory()).map((entry) => entry.name)
      if (locales.length) warnings.push({
        code: 'unsupported-config',
        message: `Docusaurus localized content was skipped; only the default locale was imported. Skipped locales: ${locales.join(', ')}.`,
        source: 'i18n',
      })
    }
  }
  // A Docusaurus MDX page can import its own local components (relative or
  // `@site/...`) and bare npm packages the same way a Mintlify page can; the
  // same bounded component graph and import-stripping logic applies to
  // either source, rooted at whichever project actually owns the pages.
  const componentRoot = mintlifyProjectRoot ?? docusaurusProjectRoot ?? repositoryDir
  const componentMigrator = platform === 'mintlify' || platform === 'docusaurus'
    ? createComponentMigrator(componentRoot, warnings, componentSourceIdentity(options.sourceUrl, repositoryDir, componentRoot))
    : undefined
  let docsConfig: MigrationDocsConfig = { tabs: [] }
  const referenceMap = new Map<string, { navigationId: string; locale?: string }>()
  const exactReferenceMap = new Map<string, { navigationId: string; locale?: string }>()
  const referenceOrder = new Map<string, number>()
  let docusaurusSidebars: DocusaurusSidebars | null = null
  let mintlifyConfig: Record<string, unknown> | null = null
  let fernRawConfig: Record<string, unknown> | null = null
  let fernApiName: string | undefined
  let fernApiNameExplicit = false
  let fernApiTabLabel: string | undefined

  if (platform === 'mintlify') {
    try {
      const config = readMintlifyConfig(mintlifyProjectRoot ?? repositoryDir)
      if (config) {
        mintlifyConfig = config
        const projected = projectMintlifyNavigation(config)
        docsConfig = projected.docsConfig
        warnings.push(...projected.warnings)
        for (const [index, reference] of projected.pageReferences.entries()) {
          const key = normalizedReferenceKey(reference.ref)
          // Shared source pages may appear in several language menus. The
          // projector visits the default language first; retain that primary
          // file so other locales can use the runtime's content fallback.
          if (!referenceMap.has(key)) referenceMap.set(key, reference)
          const exactKey = exactReferenceKey(reference.ref)
          if (!exactReferenceMap.has(exactKey)) exactReferenceMap.set(exactKey, reference)
          if (!referenceOrder.has(key)) referenceOrder.set(key, index)
        }
      }
    } catch (error) {
      warnings.push({
        code: 'unsupported-config',
        message: `Mintlify config could not be read: ${error instanceof Error ? error.message : String(error)}`,
      })
    }
  }

  if (platform === 'fern' && fernProjectRoot) {
    try {
      const fernConfig = readFernConfig(fernProjectRoot)
      if (fernConfig) {
        fernRawConfig = fernConfig.config
        const projected = projectFernNavigation({ config: fernConfig.config, fernRoot: fernProjectRoot })
        docsConfig = projected.docsConfig
        warnings.push(...projected.warnings)
        fernApiName = projected.apiName
        fernApiNameExplicit = projected.apiNameExplicit ?? false
        fernApiTabLabel = projected.apiTabLabel
        for (const [index, descriptor] of projected.descriptors.entries()) {
          const key = normalizedReferenceKey(descriptor.sourcePath)
          if (!referenceMap.has(key)) referenceMap.set(key, { navigationId: descriptor.navigationId })
          const exactKey = exactReferenceKey(descriptor.sourcePath)
          if (!exactReferenceMap.has(exactKey)) exactReferenceMap.set(exactKey, { navigationId: descriptor.navigationId })
          if (!referenceOrder.has(key)) referenceOrder.set(key, index)
        }
      }
    } catch (error) {
      warnings.push({
        code: 'unsupported-config',
        message: `Fern config could not be read: ${error instanceof Error ? error.message : String(error)}`,
      })
    }
  }

  if (platform === 'docusaurus') {
    try {
      docusaurusSidebars = options.docusaurusSkipSidebar || !docusaurusProjectRoot
        ? null
        : readDocusaurusSidebars(docusaurusProjectRoot)
    } catch (error) {
      warnings.push({
        code: 'unsupported-config',
        message: `Docusaurus sidebar could not be read safely: ${error instanceof Error ? error.message : String(error)} Generated navigation will be used.`,
      })
    }
  }

  const contentRoot = resolveWithin(repositoryDir, configuredDocsDir)
  if (!existsSync(contentRoot) || !lstatSync(contentRoot).isDirectory()) {
    throw new Error(`Documentation directory does not exist: ${configuredDocsDir || '.'}`)
  }
  const mintignoreMatcher = platform === 'mintlify' && mintlifyProjectRoot
    ? readMintignoreMatcher(mintlifyProjectRoot)
    : null
  const files = mintignoreMatcher
    ? scanFiles(contentRoot).filter((file) => !mintignoreMatcher.ignores(file.relativePath))
    : scanFiles(contentRoot)
  const pages: Array<MigrationPage> = []
  const assets: Array<MigrationAsset> = []
  const docusaurusDescriptors: Array<DocusaurusPageDescriptor> = []
  const seenPageIds = new Set<string>()
  const warnedFernComponents = new Set<string>()
  /** docs.yml-derived navigationId -> final id, when a page's frontmatter `slug` overrides it. */
  const fernIdRenames = new Map<string, string>()
  let skipped = 0
  let discovered = files.length

  const localeConfig = docsConfig.i18n
  const defaultPageIds = new Set([...referenceMap.values()]
    .filter((reference) => !reference.locale || reference.locale === localeConfig?.defaultLocale)
    .map((reference) => reference.navigationId))
  const routeAliases: NonNullable<MigrationDocsConfig['redirects']> = []
  const pageFiles = [...files].sort((left, right) => {
    const leftOrder = referenceOrder.get(normalizedReferenceKey(left.relativePath)) ?? Number.MAX_SAFE_INTEGER
    const rightOrder = referenceOrder.get(normalizedReferenceKey(right.relativePath)) ?? Number.MAX_SAFE_INTEGER
    return leftOrder - rightOrder || left.relativePath.localeCompare(right.relativePath)
  })
  const snippetAliases = platform === 'mintlify' && mintlifyProjectRoot
    ? globalSnippetAliases(files, repositoryDir, mintlifyProjectRoot)
    : new Map<string, string>()
  for (const file of pageFiles) {
    if (!isDocumentationExtension(file.relativePath)) continue
    // Unlike Mintlify/Docusaurus, Fern only ever serves pages reachable from
    // docs.yml (or a versions file); everything else is invisible on the
    // live site, so importing it as an "orphan" page would fabricate content
    // (and can crash a build on stray files that were never meant to render).
    if (platform === 'fern'
      && !exactReferenceMap.has(exactReferenceKey(file.relativePath))
      && !referenceMap.has(normalizedReferenceKey(file.relativePath))) {
      skipped++
      continue
    }
    const sourceSegments = file.relativePath.split('/')
    if (sourceSegments.some((segment) => SNIPPET_DIRECTORIES.has(segment.toLowerCase()))
      || (platform === 'docusaurus' && basename(file.relativePath).startsWith('_'))) {
      skipped++
      continue
    }
    const rootFilename = !file.relativePath.includes('/') ? basename(file.relativePath).toLowerCase() : ''
    if (REPOSITORY_ONLY_DOCUMENTS.has(rootFilename) && !exactReferenceMap.has(exactReferenceKey(file.relativePath))) {
      skipped++
      continue
    }
    if (!['.md', '.mdx'].includes(extname(file.relativePath).toLowerCase())) {
      skipped++
      warnings.push({ code: 'skipped-file', message: 'Only Markdown and MDX are imported without an explicit converter.', source: file.relativePath })
      continue
    }
    const size = lstatSync(file.absolutePath).size
    if (size > MAX_PAGE_BYTES) {
      skipped++
      warnings.push({ code: 'skipped-file', message: 'Page exceeded the 2 MB repository import limit.', source: file.relativePath })
      continue
    }
    const key = normalizedReferenceKey(file.relativePath)
    const referenced = exactReferenceMap.get(exactReferenceKey(file.relativePath)) ?? referenceMap.get(key)
    let locale = referenced?.locale
    let navigationId = referenced?.navigationId ?? pageIdFromReference(file.relativePath, platform === 'mintlify')
    if (!referenced && localeConfig) {
      for (const entry of localeConfig.locales) {
        const localized = mintlifyLocalizedReference(file.relativePath, entry.code, defaultPageIds)
        if (localized === file.relativePath) continue
        locale = entry.code
        navigationId = pageIdFromReference(localized, platform === 'mintlify')
        break
      }
    }
    if (!navigationId) {
      skipped++
      warnings.push({ code: 'invalid-page', message: 'Page path could not be normalized safely.', source: file.relativePath })
      continue
    }
    const isDefaultLocale = !locale || locale === localeConfig?.defaultLocale
    const id = isDefaultLocale ? navigationId : `${locale}/${navigationId}`
    let raw = inlineMdxSnippets(
      readFileSync(file.absolutePath, 'utf8'),
      file.absolutePath,
      repositoryDir,
      warnings,
      0,
      mintlifyProjectRoot ?? docusaurusProjectRoot ?? fernProjectRoot ?? repositoryDir,
      snippetAliases,
    )
    if (componentMigrator) {
      const warningsBeforeTransform = warnings.length
      raw = componentMigrator.transform(raw, file.absolutePath)
      // `transform` excludes a page itself (pushing a 'skipped-file' warning
      // for it) when it references an unsupported npm import outside JSX —
      // keeping that import would fail `next build` for the whole site. Skip
      // building this page too; `pruneMissingNavigationPages` below drops it
      // from navigation since it never joins `pages`.
      // `warning.source` is relative to `componentRoot`, which can differ
      // from `repositoryDir` (a nested Mintlify/Docusaurus project root);
      // compare absolute paths rather than the two relative forms directly.
      if (warnings.slice(warningsBeforeTransform).some((warning) => warning.code === 'skipped-file' && warning.source !== undefined
        && resolvePath(componentRoot, warning.source) === file.absolutePath)) {
        skipped++
        continue
      }
    }
    // A bare `{word}` in prose (e.g. Infisical's STYLE_GUIDE.md `{x}`) is
    // literal text on Mintlify and Docusaurus too, not just Fern — MDX
    // always evaluates `{...}` as a JS expression, so any platform's source
    // can hit the same `ReferenceError` at render. `escapeFernLiteralBraces`
    // is platform-agnostic (it only reads the page's own AST/ESM scope), so
    // run it for every platform Thally migrates from.
    if (platform === 'fern' || platform === 'mintlify' || platform === 'docusaurus') {
      raw = escapeFernLiteralBraces(raw)
    }
    if (platform === 'fern') {
      for (const name of detectUnsupportedFernComponents(raw)) {
        const key = `fern-component:${name}`
        if (warnedFernComponents.has(key)) continue
        warnedFernComponents.add(key)
        warnings.push({
          code: 'unsupported-config',
          message: `Fern component <${name}> is not supported by Thally; the page compiles but will likely fail to render. Edit or remove the tag.`,
          source: file.relativePath,
        })
      }
    }
    let docusaurusDescriptor: Omit<DocusaurusPageDescriptor, 'title'> | undefined
    const page = parseMarkdownPage({
      id,
      navigationId,
      ...(locale ? { locale } : {}),
      raw,
      platform,
      source: `${options.sourceUrl}#${relative(repositoryDir, file.absolutePath).replace(/\\/g, '/')}`,
      ...(platform === 'docusaurus' ? {
        resolveIdentity: (frontmatter, fallback) => {
          const resolved = resolveDocusaurusPageIdentity(file.relativePath, frontmatter, fallback)
          const routePrefix = options.docusaurusRoutePrefix === undefined
            ? undefined
            : trimEdgeSlashes(options.docusaurusRoutePrefix)
          if (!routePrefix) {
            docusaurusDescriptor = resolved.descriptor
            return resolved.identity
          }
          const prefixedNavigationId = resolved.identity.navigationId === 'introduction'
            ? routePrefix
            : `${routePrefix}/${resolved.identity.navigationId}`
          const prefixedStorageId = resolved.identity.id === 'introduction'
            ? routePrefix
            : `${routePrefix}/${resolved.identity.id}`
          docusaurusDescriptor = {
            ...resolved.descriptor,
            navigationId: prefixedNavigationId,
          }
          return {
            ...resolved.identity,
            id: prefixedStorageId,
            navigationId: prefixedNavigationId,
          }
        },
      } : {}),
      // A Fern page's own frontmatter `slug` replaces its whole section/folder
      // hierarchy (never just its own segment) and wins over a docs.yml slug.
      ...(platform === 'fern' ? {
        resolveIdentity: (frontmatter, fallback) => {
          const slug = typeof frontmatter.slug === 'string' ? frontmatter.slug.trim() : ''
          if (!slug) return fallback
          const overridden = pageIdFromReference(slug, true)
          if (!overridden) return fallback
          fernIdRenames.set(fallback.navigationId, overridden)
          return { ...fallback, id: overridden, navigationId: overridden }
        },
      } : {}),
    })
    if (!page) {
      skipped++
      continue
    }
    if (platform === 'mintlify' && mintlifyProjectRoot) {
      page.body = rewriteRepositoryAssetLinks(page.body, file.absolutePath, mintlifyProjectRoot)
    }
    if (platform === 'fern' && fernProjectRoot) {
      page.body = rewriteRepositoryAssetLinks(page.body, file.absolutePath, fernProjectRoot)
    }
    const mdxError = invalidMdxReason(page.body)
    if (mdxError) {
      skipped++
      warnings.push({
        code: 'skipped-file',
        message: `Page was excluded because it does not compile as MDX: ${mdxError}`,
        source: file.relativePath,
      })
      continue
    }
    // `hasAnyFunctionValuedProp` only proves a function value (a reference to
    // a page-declared function, or a function written inline) is passed as
    // *some* JSX prop; it does not know which tag receives it. A prop
    // landing on a component this migration actually extracted as
    // 'use client' (`Migrated<hash>`/`Inline<n>`) or on a Thally runtime
    // built-in already backed by a 'use client' module (`Accordion`, `Panel`,
    // `Tabs`, ... — see `CLIENT_BUILTIN_COMPONENT_TAGS` in components.ts) is
    // confirmed to cross the server/client boundary and throw at render — a
    // prop on any other tag (an unregistered/removed component) is not
    // confirmed either way, so exclusion (a last resort) is reserved for the
    // confirmed case; the unconfirmed case is warned instead, so it is never
    // silently dropped or silently shipped broken.
    const declaredNames = functionDeclaredNames(page.body)
    if (hasAnyFunctionValuedProp(page.body, declaredNames)) {
      if (propsTargetExtractedClientComponent(page.body, declaredNames)) {
        skipped++
        warnings.push({
          code: 'skipped-file',
          message: "This page passes a function to an interactive component, which can't be rendered on the server. "
            + 'Move the function into the component or edit the page manually.',
          source: file.relativePath,
        })
        continue
      }
      warnings.push({
        code: 'unsupported-config',
        message: "This page might pass a function to an interactive component, which can't be rendered on the "
          + 'server; review it manually if the built page fails to render.',
        source: file.relativePath,
      })
    }
    if (declarationsReferenceBrowserGlobal(page.body)) {
      warnings.push({
        code: 'unsupported-config',
        message: "This page defines a component that uses `document`/`window`, which isn't available when pages "
          + 'are rendered on the server. Move that code into a client component or edit the page manually.',
        source: file.relativePath,
      })
    }
    if (seenPageIds.has(page.id)) {
      skipped++
      warnings.push({ code: 'collision', message: `Multiple source files map to ${page.id}; the first file was kept.`, source: file.relativePath })
      continue
    }
    seenPageIds.add(page.id)
    pages.push(page)
    if (platform === 'mintlify') {
      const sourcePath = exactReferenceKey(file.relativePath)
      // Only literal portable paths become Next redirects: source filenames
      // must never introduce route patterns such as `:param` or wildcards.
      if (sourcePath !== page.id && /^[A-Za-z0-9_./-]+$/.test(sourcePath)) {
        routeAliases.push({ source: `/${sourcePath}`, destination: `/${page.id}`, permanent: false })
      }
    }
    if (docusaurusDescriptor) {
      docusaurusDescriptors.push({ ...docusaurusDescriptor, title: page.title })
    }
  }

  const discoveredReferenceKeys = new Set(files.map((file) => normalizedReferenceKey(file.relativePath)))
  for (const [key] of referenceMap) {
    if (!discoveredReferenceKeys.has(key)) {
      warnings.push({ code: 'missing-page', message: 'A navigation entry did not resolve to a source page.', source: key })
    }
  }

  const docusaurusAssetRoot = docusaurusProjectRoot ?? repositoryDir
  const repositoryAssets = platform === 'docusaurus' && configuredDocsDir && !options.docusaurusSkipAssets
    ? ['static', 'public'].flatMap((directory) => {
        const root = resolveWithin(docusaurusAssetRoot, directory)
        if (!existsSync(root) || !lstatSync(root).isDirectory()) return []
        return scanFiles(root).map((file) => ({
          ...file,
          relativePath: `${directory}/${file.relativePath}`,
        }))
      })
    : []
  let totalAssetBytes = 0
  for (const file of [...files, ...repositoryAssets]) {
    const firstSegment = file.relativePath.split('/', 1)[0].toLowerCase()
    if (!ASSET_EXTENSIONS.has(extname(file.relativePath).toLowerCase())) continue
    if (platform !== 'mintlify' && !ASSET_DIRECTORIES.has(firstSegment)) continue
    const size = lstatSync(file.absolutePath).size
    if (size > MAX_ASSET_BYTES || totalAssetBytes + size > MAX_TOTAL_ASSET_BYTES) {
      warnings.push({ code: 'limit-reached', message: 'An asset was skipped because the migration asset budget was exhausted.', source: file.relativePath })
      continue
    }
    const isDocusaurusStatic = platform === 'docusaurus' && firstSegment === 'static'
    const assetPath = normalizeAssetPath(firstSegment === 'public'
      ? file.relativePath.slice('public/'.length)
      : isDocusaurusStatic
        ? file.relativePath.slice('static/'.length)
        : file.relativePath)
    if (!assetPath) continue
    assets.push({ path: assetPath, content: readFileSync(file.absolutePath) })
    totalAssetBytes += size
  }

  if (files.length >= MAX_SOURCE_FILES) {
    warnings.push({ code: 'limit-reached', message: `Repository discovery stopped at ${MAX_SOURCE_FILES} files.` })
  }
  if (platform === 'docusaurus') {
    const projected = projectDocusaurusNavigation({
      sidebars: docusaurusSidebars,
      descriptors: docusaurusDescriptors,
      contentRoot,
      sourceUrl: options.sourceUrl,
      routePrefix: options.docusaurusRoutePrefix,
    })
    docsConfig = projected.docsConfig
    warnings.push(...projected.warnings)
    for (const page of projected.generatedPages) {
      if (seenPageIds.has(page.id)) continue
      seenPageIds.add(page.id)
      pages.push(page)
    }
    const descriptorByNavigationId = new Map(
      docusaurusDescriptors.map((descriptor) => [descriptor.navigationId, descriptor]),
    )
    for (const page of pages) {
      const descriptor = descriptorByNavigationId.get(page.navigationId)
      if (descriptor) page.body = rewriteDocusaurusLinks(page.body, descriptor, docusaurusDescriptors)
    }
  }
  if (platform === 'fern' && fernIdRenames.size > 0) {
    const renamedRoute = (route: string): string => {
      const renamed = fernIdRenames.get(route.replace(/^\//, ''))
      return renamed ? `/${renamed}` : route
    }
    const renamePages = (nodes: Array<string | MigrationNavigationGroup>): Array<string | MigrationNavigationGroup> =>
      nodes.map((node) => typeof node === 'string'
        ? fernIdRenames.get(node) ?? node
        : { ...node, pages: renamePages(node.pages) })
    for (const page of pages) {
      page.body = rewriteFernIdRenameLinks(page.body, fernIdRenames)
    }
    docsConfig = {
      ...docsConfig,
      tabs: docsConfig.tabs.map((tab) => ({
        ...tab,
        ...(tab.pages ? { pages: renamePages(tab.pages) } : {}),
        ...(tab.groups ? { groups: renamePages(tab.groups) as Array<MigrationNavigationGroup> } : {}),
      })),
      ...(docsConfig.redirects ? {
        redirects: docsConfig.redirects.map((redirect) => ({
          ...redirect,
          source: renamedRoute(redirect.source),
          destination: renamedRoute(redirect.destination),
        })),
      } : {}),
    }
  }
  if (docsConfig.tabs.length === 0) docsConfig = buildNavigationFromPages(pages)
  // A repo-wide scan for *any* `openapi.yml`/`.json` file cannot tell one
  // API's spec from another's, so once an explicit `api-name` names a
  // specific API, that naive scan is never consulted as a fallback (the root
  // `generators.yml` rule is in `fernOpenApiCandidateDirs`). Without an
  // explicit `api-name` there is only ever one API on the site, so the naive
  // scan remains safe.
  const openApi = platform === 'fern' && fernProjectRoot
    ? findFernConfiguredOpenApi(fernProjectRoot, repositoryDir, fernApiName, fernApiNameExplicit)
      ?? (fernApiNameExplicit ? null : findOpenApi(files))
    : findConfiguredMintlifyOpenApi(mintlifyConfig, files) ?? findOpenApi(files)
  if (openApi) {
    const filename = basename(openApi.relativePath)
    if (!assets.some((asset) => asset.path === filename)) {
      assets.push({ path: filename, content: readFileSync(openApi.absolutePath) })
    }
    docsConfig = injectOpenApi(docsConfig, filename, platform === 'fern' ? fernApiTabLabel : undefined)
  } else if (platform === 'fern' && fernProjectRoot && fernApiName !== undefined && fernDefinitionExists(fernProjectRoot, fernApiName)) {
    warnings.push({
      code: 'unsupported-config',
      message: 'This API is defined with a Fern Definition, not an OpenAPI/AsyncAPI document; generating a spec from a Fern Definition is not supported. Export an OpenAPI document and reference it from generators.yml, or add it manually.',
    })
  } else if (platform === 'fern' && fernProjectRoot && fernApiName !== undefined) {
    // Neither an OpenAPI/AsyncAPI spec nor a Fern Definition could be found
    // for this `api:` node — the API tab was silently dropped from the nav.
    // Name the node so the user knows which one to fix.
    const checked = fernOpenApiCandidateDirs(fernProjectRoot, fernApiName, fernApiNameExplicit)
      .map((dir) => relative(repositoryDir, resolvePath(dir, 'generators.yml')).replace(/\\/g, '/'))
    if (!fernApiNameExplicit) checked.push('any openapi or swagger file in the repository')
    warnings.push({
      code: 'unsupported-config',
      message: checked.length
        ? `No OpenAPI/AsyncAPI spec could be found for the "${fernApiName}" API. Checked: ${checked.join(', ')}. Point generators.yml at a spec file that exists.`
        : `No OpenAPI/AsyncAPI spec could be found for the "${fernApiName}" API, because its api-name is not a valid folder name. Add the spec manually.`,
    })
  }
  if (platform === 'mintlify') {
    const sources = new Set((docsConfig.redirects ?? []).map((redirect) => redirect.source))
    const aliases = routeAliases.filter((redirect) => !sources.has(redirect.source))
    if (aliases.length > 0) docsConfig = { ...docsConfig, redirects: [...(docsConfig.redirects ?? []), ...aliases] }
    docsConfig = addMintlifyHomepageRedirects(addMintlifyDirectoryRedirects(docsConfig, pages), pages)
  }

  if (platform === 'docusaurus' && docusaurusProjectRoot && !options.docusaurusSkipPlugins) {
    for (const plugin of additionalDocusaurusPluginRoots(repositoryDir, docusaurusProjectRoot)) {
      if (plugin.docsDir === configuredDocsDir) continue
      const pluginBundle = migrateRepository({
        ...options,
        docsDir: plugin.docsDir,
        platform: 'docusaurus',
        docusaurusRoutePrefix: plugin.routePrefix,
        docusaurusSkipPlugins: true,
        docusaurusSkipSidebar: true,
        docusaurusSkipAssets: true,
      })
      for (const page of pluginBundle.pages) {
        if (seenPageIds.has(page.id)) continue
        seenPageIds.add(page.id)
        pages.push(page)
      }
      const assetPaths = new Set(assets.map((asset) => asset.path))
      for (const asset of pluginBundle.assets) {
        if (assetPaths.has(asset.path)) continue
        assetPaths.add(asset.path)
        assets.push(asset)
      }
      const pluginLabel = plugin.routePrefix
        .split(/[-_/]/)
        .filter(Boolean)
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ')
      docsConfig.tabs.push(...pluginBundle.docsConfig.tabs.map((tab, index) => ({
        ...tab,
        tab: index === 0 ? pluginLabel : `${pluginLabel}: ${tab.tab}`,
      })))
      warnings.push(...pluginBundle.warnings)
      discovered += pluginBundle.stats.discovered
      skipped += pluginBundle.stats.skipped
    }
  }

  // Pages skipped above (invalid MDX, a client-boundary function prop, an id
  // collision) never entered `pages`, but the nav was projected from the raw
  // source config and may still reference their ids. Drop those dangling
  // references so `thally check` never reports a nav entry with no MDX file.
  docsConfig = pruneMissingNavigationPages(docsConfig, new Set(pages.map((page) => page.navigationId)))

  if (pages.length === 0) throw new Error('No importable Markdown or MDX pages were found in the repository.')
  const themeColors = mintlifyConfig
    ? mintlifyThemeColors(mintlifyConfig.colors)
    : fernRawConfig ? fernThemeColors(fernRawConfig.colors) : undefined
  return {
    sourceUrl: options.sourceUrl,
    sourceKind: 'repository',
    platform,
    pages,
    assets,
    ...(componentMigrator ? { componentFiles: componentMigrator.files() } : {}),
    docsConfig,
    ...(mintlifyConfig ? {
      site: {
        ...(typeof mintlifyConfig.name === 'string' ? { name: mintlifyConfig.name } : {}),
        ...(typeof mintlifyConfig.description === 'string' ? { description: mintlifyConfig.description } : {}),
        ...(themeColors ? { colors: themeColors } : {}),
      },
    } : fernRawConfig && (typeof fernRawConfig.title === 'string' || themeColors) ? {
      site: {
        ...(typeof fernRawConfig.title === 'string' ? { name: fernRawConfig.title } : {}),
        ...(themeColors ? { colors: themeColors } : {}),
      },
    } : {}),
    warnings,
    stats: { discovered, imported: pages.length, skipped },
  }
}
