/** Focused contracts for Docusaurus navigation, links, and localized fragments. */

import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { afterEach, describe, expect, it } from 'vitest'

import {
  addDocusaurusTranslatedHeadingAliases,
  projectDocusaurusNavigation,
  readDocusaurusSiteSettings,
  rewriteDocusaurusLinks,
  type DocusaurusPageDescriptor,
} from '../docusaurus.js'
import type { MigrationPage } from '../types.js'

const roots: Array<string> = []
function fixture(): string {
  const root = mkdtempSync(join(tmpdir(), 'thally-docusaurus-focused-'))
  roots.push(root)
  return root
}

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
})

describe('Docusaurus projection', () => {
  it('resolves a category metadata link to a local document id', () => {
    const root = fixture()
    mkdirSync(join(root, 'api/themes'), { recursive: true })
    writeFileSync(join(root, 'api/themes/_category_.yml'), 'label: Themes\nlink:\n  type: doc\n  id: themes-overview\n')
    const descriptors: Array<DocusaurusPageDescriptor> = [
      { sourcePath: 'api/themes/overview.mdx', docId: 'api/themes/themes-overview', navigationId: 'api/themes', title: 'Themes', sidebarPosition: 0 },
      { sourcePath: 'api/themes/classic.mdx', docId: 'api/themes/classic', navigationId: 'api/themes/classic', title: 'Classic' },
    ]
    const result = projectDocusaurusNavigation({ sidebars: null, descriptors, contentRoot: root, sourceUrl: 'https://example.com' })
    expect(result.docsConfig.tabs[0].pages).toEqual([{ group: 'API', pages: [{ group: 'Themes', pages: ['api/themes', 'api/themes/classic'] }] }])
    expect(result.warnings.filter((warning) => warning.code === 'missing-page')).toEqual([])
  })

  it('interleaves autogenerated categories and pages by authored position', () => {
    const root = fixture()
    mkdirSync(join(root, 'middle'))
    writeFileSync(join(root, 'middle', '_category_.json'), '{"label":"Middle","position":2}')
    const descriptors: Array<DocusaurusPageDescriptor> = [
      { sourcePath: '03-last.md', docId: 'last', navigationId: 'last', title: 'Last', sidebarPosition: 3 },
      { sourcePath: '01-first.md', docId: 'first', navigationId: 'first', title: 'First', sidebarPosition: 1 },
      { sourcePath: 'middle/intro.md', docId: 'middle/intro', navigationId: 'middle/intro', title: 'Middle intro' },
    ]
    const result = projectDocusaurusNavigation({ sidebars: null, descriptors, contentRoot: root, sourceUrl: 'https://example.com' })
    expect(result.docsConfig.tabs[0].pages).toEqual([
      'first', { group: 'Middle', pages: ['middle/intro'] }, 'last',
    ])
  })

  it('uses the text navbar title when the logo stanza is commented out', () => {
    const root = fixture()
    writeFileSync(join(root, 'docusaurus.config.ts'), `export default {
      title: 'Docs', themeConfig: { navbar: { title: 'Docmost',
        // logo: { src: 'img/logo.svg' },
      } },
    }`)
    expect(readDocusaurusSiteSettings(root)).toMatchObject({
      name: 'Docs', navbarTitle: 'Docmost', defaultColorMode: 'light',
    })
    expect(readDocusaurusSiteSettings(root).logo).toBeUndefined()
  })

  it('reads a static default color mode from the theme config', () => {
    const root = fixture()
    writeFileSync(join(root, 'docusaurus.config.ts'), `export default {
      themeConfig: { colorMode: { defaultMode: 'dark' } },
    }`)
    expect(readDocusaurusSiteSettings(root).defaultColorMode).toBe('dark')
  })
})

describe('Docusaurus links', () => {
  const current: DocusaurusPageDescriptor = {
    sourcePath: 'intro.md', docId: 'intro', navigationId: 'introduction', title: 'Intro',
  }

  it('normalizes mounted asset references only when the copied asset exists', () => {
    const externalized: Array<string> = []
    const body = [
      '![Logo](/docs/img/logo.svg?raw=1#preview)',
      '<img src="/docs/img/logo.svg" />',
      '[Guide](/docs/guide)',
      '[Missing](/docs/img/missing.svg)',
      '```md',
      '![Example](/docs/img/logo.svg)',
      '```',
    ].join('\n')
    const output = rewriteDocusaurusLinks(body, current, [current, {
      sourcePath: 'guide.md', docId: 'guide', navigationId: 'guide', title: 'Guide',
    }], {
      assetPaths: new Set(['img/logo.svg']),
      sourceOrigin: 'https://docs.example.com',
      onExternalLink: (target) => externalized.push(target),
    })
    expect(output).toContain('![Logo](/img/logo.svg?raw=1#preview)')
    expect(output).toContain('<img src="/img/logo.svg" />')
    expect(output).toContain('[Guide](/guide)')
    expect(output).toContain('[Missing](https://docs.example.com/docs/img/missing.svg)')
    expect(output).toContain('![Example](/docs/img/logo.svg)')
    expect(externalized).toEqual(['/docs/img/missing.svg'])
  })
})

function page(navigationId: string, body: string, sourcePath: string): MigrationPage {
  return {
    id: navigationId,
    navigationId,
    title: navigationId,
    description: '',
    keywords: [],
    body,
    source: `https://github.com/acme/docs#${sourcePath}`,
  }
}

describe('translated Docusaurus headings', () => {
  it('adds fragments for localized cross-page links and keeps explicit IDs', () => {
    const original = page('guide', '## Overview\n\n### Configure', 'docs/guide.md')
    const translated = page('de/guide', '<a id="einstellungen"></a>\n## Überblick\n\n### Einrichten',
      'i18n/de/docusaurus-plugin-content-docs/current/guide.md')
    const linkingPage = page('de/intro', '[Overview](/de/guide#overview)',
      'i18n/de/docusaurus-plugin-content-docs/current/intro.md')
    addDocusaurusTranslatedHeadingAliases([original, translated, linkingPage])
    expect(translated.body).toContain('<a id="overview"></a>\n## Überblick')
    expect(translated.body).toContain('<a id="einstellungen"></a>\n<a id="overview"></a>')
    expect(translated.body).toContain('<a id="configure"></a>\n### Einrichten')
    expect(linkingPage.body).toContain('[Overview](/de/guide#overview)')
  })

  it('leaves edited heading outlines and ambiguous source IDs alone', () => {
    const original = page('guide', '## Overview\n## Overview', 'docs/guide.md')
    const translated = page('de/guide', '## Überblick\n### Details',
      'i18n/de/docusaurus-plugin-content-docs/current/guide.md')
    addDocusaurusTranslatedHeadingAliases([original, translated])
    expect(translated.body).toBe('## Überblick\n### Details')
  })

  it('maps an explicit source ID without replacing a translated explicit ID', () => {
    const original = page('guide', '<a id="stable-en"></a>\n## Overview', 'docs/guide.md')
    const translated = page('de/guide', '<a id="stable-de"></a>\n## Überblick',
      'i18n/de/docusaurus-plugin-content-docs/current/guide.md')
    addDocusaurusTranslatedHeadingAliases([original, translated])
    expect(translated.body).toBe('<a id="stable-de"></a>\n<a id="stable-en"></a>\n## Überblick')
  })

  it('pairs translated root pages with the default introduction route', () => {
    const original = page('introduction', '## Overview', 'docs/intro.md')
    const translated = page('de', '## Überblick',
      'i18n/de/docusaurus-plugin-content-docs/current/intro.md')
    addDocusaurusTranslatedHeadingAliases([original, translated])
    expect(translated.body).toBe('<a id="overview"></a>\n## Überblick')
  })
})
